# For문

```{r}
for(i in 1:10){
  print(i)
}
```

```{r}
for(i in c(1,3,5)){
  print(i)
}
```

1\~100까지의 홀수만 출력하기

```{r}
for(i in c(seq(1, 100, 2))){
  print(i)
}
```

1\~100까지의 홀수만 출력

```{r}
for(i in 1:10){
 cat(paste(i, "=>", sqrt(i), "\n"))
}



```

1부터 100까지의 짝수의 합계 구하기

```{r}
data <- 1:100
length(data)

cat("1부터 100까지의 짝수의 합계의 합은 ", sum(c(seq(0,length(data),2))), "입니다.")


```

```{r}
sum(ifelse(data %% 2 ==0, data, 0))
for(i in sum(c(seq(0, length(data),2)))) {
  print(i)
}


```

```{r}
for(i in data){
  if(data %% 2 ==0){
    sum(i)
  }
}
```

```{r}

```

```{r}
data <- excel$q3
#sumEven, sumOdd 초기화 
sumEven <- sumOdd <- 0

for(i in data){
  if(i %% 2 == 0){
    sumEven = sumEven +i
  }else{
    sumOdd = sumOdd +i
  }
}
cat("홀수의 합은", sumOdd, "이고 짝수의 합은", sumEven, "입니다.")
```

```{r}
for(i in 1:9){
  cat("2 X", i, "=", 2*i, "\n")
}
```

```{r}
gugu <- function(){
  for(i in 1:9){
  cat("2 X", i, "=", 2*i, "\n")
  }
}
```

```{r}
gugu() #...??
```

```{r}
gugu2 <- function(n){
  for(i in 1:9){
    
  cat( n," X ", i, "=", n*i,"\n")
    
  }
}
```

```{r}
gugu2(4)
```

```{r}
gugu3 <- function(n,m){
   for(i in 1:m){
    
  cat( n," X ", i, "=", n*i,"\n")
    
  }
}
```

```{r}
gugu3(2,12)
```

```{r}
m <- seq(2,8,2)
n <- seq(2,8,2)
gugu4 <- function(n,m){
   for(i in 1:m){
    
  cat( n," X ", i, "=", n*i,"\n")
    
  }
}
```

```{r}
gugu4(2,12)
```

```{r}
score <- c(85, 95, 89)
name <- c("유비", "관우", "장비")

j <- 1
for(i in score){
  cat(name[j],":",i,"\n")
  j=j+1
}
```

```{r}
cat(paste(name, ":", score, "\n"), seq="")
```

```{r}
## 구구단도 cat으로 해보기 
```

## While

```{r}
i <- 0
while(i < 10){
  i = i + 1
  print(i)
}
```

```{r}
i <- 0
while(T){
  i=i+1
  print(i)
  if(i>9){
    break
  }
}
```

# repeat

```{r}
i <- 0
repeat{
  i= i+1
  if(i>10){
    break
  }
  print(i)
}
```
