# 🐭 몬테카를로 시뮬레이션

-데이터가 없을 경우에 만들어서 실행해보는 것, 가정해서 실행해 보는 것

-예를 들어 동전 던졌을 때 정말 50:50인지?? \>\> 다 던져보기 or 컴퓨터 난수 사용

### 동전의 앞면 뒷면 시뮬레이션

```{r}
runif(1, 0, 6)
```

```{r}
x <- runif(1)
if(x <= 1/2){
  result = 0  #Front
}else{
  result = 1  #Rear
}
print(result)

```

```{r}
coin <- function(n){
  count1 = 0
  count2 = 0
  
  for (i in 1:n) {
    if(runif(1) <= 1/2){
      count1 = count1 + 1
    }else{
      count2 = count2 + 1
    }
  }
  
  cat("앞면:", count1, "\n")
  cat("뒷면:", count2, "\n")
  cat("-------------------","\n")
}
```

```{r}
coin(10)
coin(100)
coin(1000)
coin(10000)
coin(100000)
coin(1000000)


```

# 가위, 바위, 보

```{r}
count=c('가위','바위','보')
sample(count, 1)
```

```{r}
rock <- function(n){
  count1 =0
  count2 =0
  count3 =0
  
  for (i in 1:n) {
    if(sample(count, 1) <= '가위'){
      count1 = count1 + 1
    
    }else if(sample(count, 1) <= '바위'){
      count2 = count2 +1
    }else{
      count3 = count3 + 1
    }
  }
  
  cat("가위:", count1, "\n")
  cat("바위:", count2, "\n")
  cat("보:", count3, "\n")

  cat("-------------------","\n")
}
```

```{r}
rock(10)
```

```{r}
runif(1)*3
```

선생님 답

```{r}
rock <- function(n){
  rock =0
  scissor =0
  paper =0
  
  for (i in 1:n) {
    x <- trunc(runif(1) *3) + 1
    if(x == 1) scissor = scissor + 1
    if(x == 2) rock = rock + 1
    if(x == 3) paper = paper + 1
    
  }
  
  cat("가위:\t", scissor, "\n")
  cat("바위:\t", rock, "\n")
  cat("보:\t", paper, "\n")

  cat("-------------------","\n")
}
```

```{r}
rock(10)
rock(100)
rock(1000)
rock(10000)
rock(100000)
rock(1000000)
```

## 주사위 시뮬레이션

```{r}
trunc(runif(6)*6) +1
```

```{r}
dice <- function(n){
  no1 =0
  no2 =0
  no3 =0
  no4 =0
  no5 =0
  no6 =0
  
  
  for (i in 1:n) {
    x <- trunc(runif(1) *6) + 1
    if(x == 1) no1 = no1 + 1
    if(x == 2) no2 = no2 + 1
    if(x == 3) no3 = no3 + 1
    if(x == 4) no4 = no4 + 1
    if(x == 5) no5 = no5 + 1
    if(x == 6) no6 = no6 + 1
    
  }
  cat("Throw : ", n, "\n")
  cat("1 =>\t", no1, "\n")
  cat("2 =>\t", no2, "\n")
  cat("3 =>\t", no3, "\n")
  cat("4 =>\t", no4, "\n")
  cat("5 =>\t", no5, "\n")
  cat("6 =>\t", no6, "\n")

  cat("-------------------","\n")
}

```

```{r}
dice(10)
dice(100)
dice(1000)
dice(10000)
dice(100000)
dice(1000000)
```

선생님 답

```{r}
rep(0,6)
```

```{r}
dice <- function(n){
  
  diceFace <- rep(0, 6)
  
  cat("Throw :", n, "\n")
  
  for(i in 1:n){
    x <- trunc(runif(1) * 6) + 1
    diceFace[x] = diceFace[x] + 1
  }
  for(i in 1:length(diceFace)){
    cat("No", i, "=>", diceFace[i], "\n")
  }
  cat("--------------------\n")
}
```

```{r}
options(scipen = 100) #지수 안보이기

dice(10)
dice(100)
dice(1000)
dice(10000)
dice(100000)
dice(1000000)
```

1e+06: 지수
