# MySql 연결

```{r}
version
```

r에서 java사용 가능함: 패키지에서 RJava, RMysql 설치

```{r}
library(RMySQL)
```

### DB 연동

```{r}
conn <- dbConnect(MySQL(),
                  dbname = 'RSQL',
                  user = 'root',
                  password = 'qwer1234',
                  host = '127.0.0.1',
                  )
```

### 테이블 목록 불러오기

```{r}
dbListTables(conn)
```

### 컬럼목록 불러오기

```{r}
dbListFields(conn, 'score')[]
```

\>\>벡터

### query

select문

```{r}
result <- dbGetQuery(conn, 'select count(*) from score')
result
```

\*DB 테이블 만들때 데이터타입 int해줘서 dbl로 나옴

insert

```{r}
dbSendQuery(conn, 'insert into score values (2, 90, 90, 90)')
```

```{r}
result <- dbGetQuery(conn, 'select * from score')
result
```

update

```{r}
dbSendQuery(conn, 'update score set korean=90, english=80, mathematics=70 where id=2')
result <- dbGetQuery(conn, 'select * from score')
result
```

delete

```{r}
dbSendQuery(conn, 'delete from score where id=2')
result <- dbGetQuery(conn, 'select * from score')
result
```

delete로 전부 지우기

```{r}
dbSendQuery(conn, 'delete from score')
result <- dbGetQuery(conn, 'select * from score')
result
```

### MySQL로 csv file 올리기

```{r}
data <- read.csv('./Data/score.csv', head = F)
colnames(data) <- c('id', 'korean', 'english', 'mathematics')
head(data)
```

```{r}
dbWriteTable(conn, 'score', data, overwrite=T, row.names = F)
result <- dbGetQuery(conn, 'select * from score')
result
```

-workbench에서 하단 두 문장 실행시켜줘야됨

show variables like 'local_infile';

set global local_infile = 1;

```{r}
str(result)
```

### 기존 Table에 Data 추가하기

```{r}
data <- read.csv('./Data/score2.csv', head = F)
colnames(data) <- c('id', 'korean', 'english', 'mathematics')
data
```

```{r}
dbWriteTable(conn, 'score', data, overwrite=F, row.names = F, append = T)
```

```{r}
result <- dbGetQuery(conn, 'select * from score where id > 5')
result
```

### Disconnect

```{r}
dbDisconnect(conn)
```
