# 데이터 정제 Flow

```{r}
seoul <- read.table("./Data/trafficAccident_2011_2019.txt", header = T)
head(seoul)
```

### 불필요한 열행 제거

```{r}
seoul <- seoul[-c(1:3), -4]
seoul

```

### 컬럼 이름 정리

```{r}
colnames(seoul) <- c('기간', '자치구별', '구분', paste(1:12, '월', sep=''))
head(seoul, 10)
```

### rownames 정리

```{r}
rownames(seoul) <- c()
tail(seoul, 10)
```

### 현재 DataSet의 row수 계산

```{r}
9 * 3 * 25
#675 tail(seoul)행의 번호와 일치하지 않으므로 각 컬럼별 unique를 봐야 함 (다른 데이터가 끼여 있는 것 같다.)
```

### 컬럼별 Data 확인

```{r}
unique(seoul$기간)
```

```{r}
unique(seoul$자치구별)
```

> 합계를 제거 (\>+enter)

```{r}
unique(seoul$구분)
```

> 자치구별에 합계라고 되어 있는 row 제거

```{r}
row_hap <- as.numeric(rownames(subset(seoul, 자치구별 == '합계')))

seoul <- seoul[-row_hap, ]
```

```{r}
nrow(seoul)
```

```{r}
length(unique(seoul$자치구별))
```

\-\-\-\-\-\-\-\--

# 전처리하여 new dataframe 만들기

```{r}
#안 바뀌는 데이터 수 확인(상수)
9 * 25 * 12  #2700
```

```{r}
년도 <- rep(2011:2019, each = (25*12))
월 <- rep(1:12, 9*25)
자치구명 <- rep(rep(unique(seoul$자치구별), each=12),9)
```

```{r}
length(년도)
length(월)
length(자치구명)
```

### 새로운 Dataframe 제작

```{r}
newSeoul <- data.frame(년도, 월, 자치구명)
head(newSeoul)
nrow(newSeoul)
```

### 기존 data를 new format에 맞추기

```{r}
temp <- c()
for(i in seq(1, 673, 3)){
  temp <- rbind(temp, t(seoul[i:(i+2), 4:ncol(seoul)]))
}
head(temp)
```

### rownames 지우기

```{r}
rownames(temp) <- c()
tail(temp)
```

```{r}
newSeoul <- cbind(newSeoul, temp)
head(newSeoul)
```

### newSeoul의 컬럼 이름 변경

```{r}
colnames(newSeoul) <- c('년도','월','자치구명','발생건수','사망자수','부상자수')
head(newSeoul)
tail(newSeoul)
```

\-\--

# newSeoul 정제하기

```{r}
for(i in 1:ncol(newSeoul)){
  print(sum(is.na(newSeoul[,i])))
}
```

### 내부구조 확인

```{r}
str(newSeoul)
```

### 각 열의 -을 0으로 변경하기

```{r}
library(stringr)
```

```{r}
for(i in 4:ncol(newSeoul)){
  newSeoul[,i] <- str_replace_all(newSeoul[,i],'-','0')
}
str(newSeoul)
```

### 천단위 쉼표 제거

```{r}
for(i in 4:ncol(newSeoul)){
  newSeoul[,i] <- str_remove_all(newSeoul[,i],',')
}
tail(newSeoul)
```

### 월 Data의 Type을 숫자로 변경하기

```{r}
for(i in 4:ncol(newSeoul)){
  newSeoul[,i] <- as.numeric(newSeoul[,i])
}
str(newSeoul)
```

```{r}
head(newSeoul)
```

### 저장하기

```{r}
write.csv(newSeoul, "./data/newSeoul.csv", row.names = F)
```

## 데이터 확인 작업

```{r}
plot(newSeoul$발생건수, newSeoul$부상자수)
```
